views/admin.py
from flask import Blueprint, render_template, request, flash, redirect, url_for

import auth
import forms

from service.user_service import UserService
from service.program_service import ProgramService
from service.druzina_service import DruzinaService
from service.druzina_service import NovaDruzinaService
from service.event_service import EventService

admin = Blueprint('admin', __name__)

@admin.route('/registrace', methods=['GET', 'POST'])
@auth.login_required
@auth.roles_required('administrator')
def view_admin_registration_page():
    form = forms.RegistrationForm(request.form)
    druziny = DruzinaService.get_all()
    rodice = UserService.get_all_parents()
    form.id_druzina_clenem.choices = [(item['id_druzina'], item['jmeno']) for item in druziny]
    form.id_druzina_clenem.choices.append((None, 'neni clenem'))
    form.id_druzina_vede.choices = [(item['id_druzina'], item['jmeno']) for item in druziny]
    form.id_druzina_vede.choices.append((None, 'nevede druzinu'))
    form.id_rodice.choices = [(item['id_user'], item['jmeno'] + ' ' + item['prijmeni']) for item in rodice]
    form.id_rodice.choices.append((None, 'nema rodice'))

    if request.method == 'POST':
        UserService.register_user(
            login=request.form['login'],
            heslo=request.form['heslo'],
            rodne_cislo=request.form['rodne_cislo'],
            jmeno=request.form['jmeno'],
            prijmeni=request.form['prijmeni'],
            adresa=request.form['adresa'],
            telefon=request.form['telefon'],
            email=request.form['email'],
            datum_narozeni=request.form['datum_narozeni'],
            id_rodice=request.form['id_rodice'],
            id_role=request.form['id_role'],
            id_druzina_vede=request.form['id_druzina_vede'],
            id_druzina_clenem=request.form['id_druzina_clenem']
        )
        flash('Uspesne zaregistrovano')
    return render_template('admin_registration_page.jinja', register_form=form)

@admin.route('/programs')
@auth.login_required
@auth.roles_required('administrator')
def view_admin_programs_page():
    return render_template('admin_programs_page.jinja')

@admin.route('/newprogram', methods=['GET', 'POST'])
@auth.login_required
@auth.roles_required('administrator')
def view_admin_newprogram_page():
    form = forms.NewProgramForm(request.form)
    if request.method == 'POST':
        ProgramService.new_program(
            misto=request.form['misto_programu'],
            popis=request.form['popis'],
            delka=request.form['delka'],
            doporuceny_vek=request.form['doporuceny_vek']
        )
        flash('Akce přidána')
    return render_template('admin_newprogram_page.jinja', newprogram_form=form)

@admin.route('/newbigevent', methods=['GET', 'POST'])
@auth.login_required
@auth.roles_required('administrator')
def view_admin_newbigevent_page():
    form = forms.AkceSProgramemForm(request.form)
    druziny = DruzinaService.get_all()
    form.druzina.choices = [(item['id_druzina'], item['jmeno']) for item in druziny]
    vedouci = UserService.get_vsechny_vedouci()
    form.vedouci.choices = [(item['id_user'], item['prijmeni']) for item in vedouci]
    if request.method == 'POST':
        ProgramService.new_program(
            misto=request.form['misto_programu'],
            popis=request.form['popis_programu'],
            delka=request.form['delka'],
            doporuceny_vek=request.form['doporuceny_vek']
        )
        EventService.new_big_event(
            jmeno=request.form['jmeno'],
            datum=request.form['datum'],
            misto=request.form['misto'],
            zacatek_akce=request.form['zacatek_akce'],
            konec_akce=request.form['konec_akce'],
            popis=request.form['popis'],
            druzina=form.druzina.data,
            vedouci=form.vedouci.data
        )
        flash('Akce s programem přidána')
    return render_template('admin_newbigevent_page.jinja', form=form)

@admin.route('/newgroup', methods=['GET', 'POST'])
@auth.login_required
@auth.roles_required('administrator')
def view_admin_newgroup_page():
    form = forms.NewGroupForm(request.form)

    if request.method == 'POST':
        NovaDruzinaService.new_group(
            request.form['jmeno'],
            request.form['vek'],
            request.form['popis']
        )
        flash('Nová skupina byla založena')

    return render_template('admin_newgroup_page.jinja', form=form)

@admin.route('/showprograms')
@auth.login_required
@auth.roles_required('administrator')
def view_admin_showprograms_page():
    programs = ProgramService.get_all_programs()
    return render_template('admin_showprograms_page.jinja',program=programs)

@admin.route('/edit_program',methods=['GET','POST'])
@auth.login_required
@auth.roles_required('administrator')
def edit_program():
    edit_form = forms.NewProgramForm(request.form)
    program = dict(ProgramService.get_program_by_id(request.args.get('id_program')))
    edit_form.misto_programu.data = program['misto_program']
    edit_form.popis.data = program['popis_program']
    edit_form.delka.data = program['delka']
    edit_form.doporuceny_vek.data = program['doporuceny_vek']
    if request.method == 'POST':
        program_data = [request.form.get('misto_programu'), request.form.get('popis'), request.form.get('delka'), request.form.get('doporuceny_vek'),
        int(program['id_program'])]
        ProgramService.update_program_by_id(program_data)
        flash('Program byl upraven')
        return redirect(url_for('admin.view_admin_showprograms_page'))
    return render_template('admin_programchanges_page.jinja',edit_form=edit_form)

@admin.route('/delete_program/<int:id>')
@auth.login_required
@auth.roles_required('administrator')
def delete_program(id):
    ProgramService.delete_program_with_id(id)
    flash('Program byl smazán')
    return redirect(url_for('admin.view_admin_showprograms_page'))

views/events_more.py
from flask import Blueprint, render_template, session, request, flash, redirect, url_for
from flask_mail import Message

import auth
import forms


from service.user_service import UserService
from service.event_service import EventService

events_more = Blueprint('events_more', __name__)

@events_more.route('/')
@auth.login_required
def view_events_page():
    import app

    akce = EventService.get_all_events_with_program()
    druziny = EventService.get_all_events_with_druzina()
    je_prihlaseno_dite, deti, dochazka, child_id = None, None, None, None
    child_name = ''

    if session['role'] not in ('vedouci', 'administrator'):
        akce = list(filter(lambda zaznam: zaznam['je_public'] == 1, akce))

        if session['role'] == 'rodic':
            child_id = request.args.get('child_id', None, int)
            deti = UserService.get_children_by_parent(session['id'])
            id_event = request.args.get('id_event', None, int)

            if child_id is None and len(deti) > 0:
                child_id = deti[0]['id_user']

            if child_id is not None and len(deti) > 0:
                child_name = UserService.get_user_by_id(child_id)['jmeno'] + ' ' + UserService.get_user_by_id(child_id)[
                    'prijmeni']

            dojde = request.args.get('dojde', default=False, type=lambda v: v.lower() == 'true')

            if dojde is not None and id_event is not None:
                EventService.change_dochazka(dojde, child_id, id_event)
                if dojde:
                    flash('Uživatel ' + child_name + ' byl úspěšně přihlášen na akci')
                else:
                    flash('Uživatel ' + child_name + ' byl úspěšně odhlášen z akce')

            if id_event is not None:
                dochazka = EventService.get_dochazka_by_user_and_akce_id(child_id, id_event)

        if session['role'] == 'dite':
            je_prihlaseno_dite = EventService.get_dochazka_by_user_and_akce_id(session['id'], akce[0]['id_akce'])
            je_prihlaseno_dite = False if je_prihlaseno_dite == None else je_prihlaseno_dite['dochazka']

            if je_prihlaseno_dite and request.args != {}:
                special_proposition = ''.join(['- ' + food + '\n' for food in request.args.values()])
                msg = Message('Zpráva z webu 1oddilorli', sender=session['email'],
                              recipients=['martinacek.n@gmail.com'])
                msg.body = f"{'Jméno a příjmění: ' + session['name']}\nSpeciální propozice:\n{special_proposition}"
                app.mail.send(msg)
                flash('Nabídka byla odeslána vedoucímu')

    elif session['role'] in ('vedouci', 'administrator') and request.args.get('id_akce'):
        EventService.set_public(request.args.get('id_akce'))
        flash('Akce byla zveřejněna')
        return redirect(url_for('events_more.view_events_page'))

    return render_template('events_page_more.jinja', akce=akce, druziny=druziny, deti=deti,
                           child_name=child_name,
                           dochazka=dochazka, child_id=child_id, je_prihlaseno_dite=je_prihlaseno_dite)

@events_more.route('/edit', methods=['GET', 'POST'])
@auth.login_required
@auth.roles_required('vedouci', 'administrator')
def edit_event():
    edit_form = forms.NewBigEventForm(request.form)
    akce = dict(EventService.get_event_by_id(request.args.get('id_akce')))
    edit_form.jmeno.data = akce['jmeno']
    edit_form.misto.data = akce['misto']
    edit_form.popis.data = akce['popis']

    if request.method == 'POST':
        akce_data = [request.form.get('jmeno'), request.form.get('datum'), request.form.get('misto'),
            request.form.get('zacatek_akce'), request.form.get('konec_akce'), request.form.get('popis'),
            int(akce['id_akce'])]
        EventService.update_event_by_id(akce_data)
        flash('Akce byla upravena')
        return redirect(url_for('events_more.view_events_page'))

    return render_template('events_edit_page.jinja', edit_form=edit_form)

@events_more.route('/delete/')
@auth.login_required
@auth.roles_required('vedouci', 'administrator')
def delete_event():
    EventService.delete_event_by_id(request.args.get('id_akce'))
    flash('Akce byla vymazána')
    return redirect(url_for('events_more.view_events_page'))


@events_more.route('/attendance/', methods=['GET', 'POST'])
@auth.login_required
@auth.roles_required('vedouci', 'administrator')
def view_attendance_page():
    children = UserService.get_all_children_by_event(request.args.get('id_akce'))

    if request.method == 'POST':
        id_akce = request.args.get('id_akce')
        form_list = dict(request.form.lists())
        form_list = list(form_list.values())
        index = 0

        while (index != len(form_list)):
            dochazka = form_list[index][0]
            index += 1

            id_user = form_list[index][0]
            index += 1

            duvod = form_list[index][0] if form_list[index][0] is not None else ''
            index += 1

            EventService.change_dochazka(dochazka, id_user, id_akce, duvod)

        flash('Docházka byla odeslána')
        return redirect(url_for('events_more.view_events_page'))

    return render_template('attendance_page.jinja',
                           children=children, id_akce=request.args.get('id_akce'),
                           jmeno_akce=request.args.get('jmeno_akce'))

views/login.py
from flask import Blueprint, render_template, session, flash, request, redirect, url_for

import auth
import forms

from service.user_service import UserService

login = Blueprint('login', __name__)

@login.route('/signin', methods=['GET', 'POST'])
def view_sign_in_page():
    form = forms.SignForm(request.form)
    if request.method == 'POST':
        user = UserService.verify(login=request.form['login'], password=request.form['password'])
        if not user:
            flash('Nespravne heslo nebo login')
        else:
            session['authenticated'] = 1
            session['id'] = user['id_user']
            session['id_druziny'] = user['id_druzina_clenem']
            session['name'] = user['jmeno'] + ' ' + user['prijmeni']
            session['login'] = user['login']
            session['email'] = user['email']
            session['role'] = user['nazev']
            return redirect(url_for('unregistered_user.view_home_page'))

    return render_template('sign_in.jinja', sign_in_form = form)

@login.route('/signout')
@auth.login_required
def signout():
    session.pop('authenticated')
    session.pop('id')
    session.pop('id_druziny')
    session.pop('name')
    session.pop('login')
    session.pop('email')
    session.pop('role')
    return redirect(url_for('unregistered_user.view_home_page'))

views/unregistered_user.py
from flask import Blueprint, render_template, session, request, flash, redirect, url_for
from flask_mail import Message

import auth
import forms

from service.user_service import UserService

unregistered_user = Blueprint('unregistered_user', __name__)

@unregistered_user.route('/')
def view_home_page():
    return render_template('home_page.jinja')

@unregistered_user.route('/events')
def view_meetings_page():
    return render_template('events_page.jinja')

@unregistered_user.route('/contacts', methods=['GET', 'POST'])
def view_contacts_page():
    from app import mail
    form = forms.EmailForm(request.form)
    if request.method == 'POST':
        msg = Message('Zpráva z webu 1oddilorli', sender=request.form['email'], recipients=['martinacek.n@gmail.com'])
        msg.body = f"E-mail odesílatele: {request.form['email']}\nObsah zprávy:\n{request.form['zprava']}"
        mail.send(msg)
        flash('Mail odeslán')
        return redirect(url_for('unregistered_user.view_contacts_page'))
    return render_template('contacts_page.jinja', email_form = form)

@unregistered_user.route('/personal_page')
@auth.login_required
def view_personal_page():
    user_personal_data = UserService.get_user_by_id(session['id'])
    deti=None

    if session['role'] == 'rodic':
        deti = UserService.get_children_by_parent(session['id'])

    return render_template('personal_page.jinja', user_personal_data=user_personal_data, deti=deti)

templates/__main.jinja
<!DOCTYPE html>
<html lang="cs">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>1. oddíl Orli</title>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="shortcut icon" href="{{ url_for('static', filename='img/orli.png')}}" type="image/x-icon">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main_styles.css') }}" type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/fonts.css') }}" type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/colors.css') }}" type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/sign_in.css') }}" type="text/css">
        {% block cssstyles %}
        {% endblock %}
    </head>
    <body>
        <!-- Navigation -->
        {% include '__nav.jinja' %}

        <main>
        <!-- Flash messages -->
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <ul class=flashes style="position: relative; top: 1em; list-style-type: none; padding-inline-start: 0.5em; margin: 0;">
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}

        <!-- Render main -->
        {% block content %}
        {% endblock %}
        </main>

        <!-- Footer -->
        {% include '__footer.jinja' %}
    </body>
</html>

templates/__nav.jinja
{% block nav %}
    <header>
        <h1> 1. oddíl Orli </h1>
        <span class="material-symbols-outlined">
            {% if session['authenticated'] %}
                <a href="{{ url_for('login.signout') }}">logout</a>
            {% else %}
                <a href="{{ url_for('login.view_sign_in_page') }}">account_circle</a>
            {% endif %}
        </span>

    </header>
    <nav>
        <ul>
            <li><a href="{{ url_for('unregistered_user.view_home_page') }}">Domů</a></li>
            {% if session['authenticated'] %}
                <li><a href="{{ url_for('events_more.view_events_page') }}">Akce</a></li>
            {% else %}
                <li><a href="{{ url_for('unregistered_user.view_meetings_page') }}">Akce</a></li>
            {% endif %}

            {% if not session['authenticated'] %}
                <li><a href="{{ url_for('unregistered_user.view_contacts_page') }}">Kontakt</a></li>
            {% endif %}


            {% if session['authenticated'] and session['role'] == 'vedouci'%}
                <li><a href="{{ url_for('unregistered_user.view_personal_page') }}">Vedoucí</a></li>
            {% elif session['authenticated'] and session['role'] == 'administrator'%}
                <li><a href="{{ url_for('admin.view_admin_programs_page') }}">Správa oddílu</a></li>
                <li><a href="{{ url_for('unregistered_user.view_personal_page') }}">Administrátor</a></li>
            {% elif session['authenticated'] and session['role'] == 'rodic'%}
                <li><a href="{{ url_for('unregistered_user.view_personal_page') }}">Rodič</a></li>
            {% elif session['authenticated'] and session['role'] == 'dite'%}
                <li><a href="{{ url_for('unregistered_user.view_personal_page') }}">Dítě</a></li>
            {% endif %}
        </ul>
    </nav>
{% endblock%}

templates/admin_newbigevent_page.jinja
{% extends '__main.jinja' %}
{% from 'macros/form_field.jinja' import render_field with context %}

{% block content %}
  <section>
    <h1>Přidat akci</h1>
    <form method=post>
        <dl>
          {{ render_field(form.jmeno) }}
          {{ render_field(form.datum) }}
          {{ render_field(form.misto) }}
          {{ render_field(form.zacatek_akce) }}
          {{ render_field(form.konec_akce) }}
          {{ render_field(form.popis) }}
          {{ render_field(form.druzina) }}
          {{ render_field(form.vedouci) }}
          <h3>Program akce</h3>
          {{ render_field(form.misto_programu) }}
          {{ render_field(form.popis_programu) }}
          {{ render_field(form.delka) }}
          {{ render_field(form.doporuceny_vek) }}
        </dl>
        <input class="register" type="submit" value="Přidat akci">
      </form>
  </section>
{% endblock %}

templates/admin_newgroup_page.jinja
{% from 'macros/form_field.jinja' import render_field with context %}
{% extends "__main.jinja" %}

{% block content %}
    <section>
        <h2> Založit novou družinu </h2>
        <form method="post">
            <dl>
                {{ render_field(form.jmeno) }}
                {{ render_field(form.nejmladsi_vek) }}
                {{ render_field(form.popis) }}
            </dl>
            <input class="register" type="submit" value="Založit">
        </form>
    </section>
{% endblock %}

templates/admin_programchanges_page.jinja
{% extends '__main.jinja' %}
{% from 'macros/form_field.jinja' import render_field with context %}

{% block content %}
  <section>
    <h2>Upravit program</h2>
      <form method=post>
      <dl>
          {{ render_field(edit_form.misto_programu) }}
          {{ render_field(edit_form.popis) }}
          {{ render_field(edit_form.delka) }}
          {{ render_field(edit_form.doporuceny_vek) }}
      </dl>
      <input class="register" type="submit" value="Uložit změny">
      </form>
  </section>
{% endblock %}

templates/admin_programs_page.jinja
{% extends '__main.jinja' %}

{% block content %}
    <section>
        <h2>Správa oddílu</h2>
        <ul>
            <li><a href="{{ url_for('admin.view_admin_registration_page') }}">Vytvořit nový účet</a></li>
            {# <li><a href="{{ url_for('admin.view_admin_newprogram_page') }}">Přidat program</a></li> #}
            <li><a href="{{ url_for('admin.view_admin_newgroup_page') }}">Založit novou družinu</a></li>
            <li><a href="{{ url_for('admin.view_admin_newbigevent_page') }}">Přidat akci</a></li>
            <li><a href="{{ url_for('admin.view_admin_showprograms_page') }}">Zobrazit programy</a></li>
        </ul>
    </section>
{% endblock %}

templates/admin_showprograms_page.jinja
{% extends '__main.jinja' %}
{# {% from 'macros/form_field.jinja' import render_field with context %} #}

{% block cssstyles %}
  <link rel="stylesheet" href="{{ url_for('static', filename='css/events_more.css') }}" type="text/css">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/events.css') }}" type="text/css">
{% endblock %}

{% block content %}   
    <section>
      <h2>Aktuální programy</h2>
          {% for p in program %}
            <ul style="list-style-type: none; padding-inline-start: 0.3em;">
              <li>Místo programu: {{ p.misto_program }}</li>
              <li>Popis: {{ p.popis_program }}</li> 
              <li>Délka: {{ p.delka }}</li> 
              <li>Doporučený věk:
              {% if p.doporuceny_vek %}
                  {{ p.doporuceny_vek }}
              {% else %}
                {{ 0 }}
              {% endif %}
              </li>
            </ul>
            <a href="{{ url_for('admin.delete_program', id=p.id_program) }}" class="button">Smazat</a>
            <a href="{{ url_for('admin.edit_program') }}?id_program={{ p.id_program }}" class="button">Upravit</a>
            

            
          {% endfor %}
    </section>
{% endblock %}

templates/events_page_more.jinja
{% extends '__main.jinja' %}

{% block cssstyles %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/events_more.css') }}" type="text/css">
{% endblock %}

{% block content %}
    <section class="child_selection">
        {% if session['authenticated'] and session['role'] == 'rodic' %}
            {% if child_name != "" %}
                <div class="dropdown-header">
                    <h2>{{ child_name }}</h2>
                </div>
                <div class="dropdown-content">
                    {% for dite in deti %}
                        <a href="?child_id={{ dite.id_user }}">{{ dite.jmeno }} {{ dite.prijmeni }}</a>
                    {% endfor %}
                </div>
            {% endif %}
        {% endif %}
    </section>
    <section>
        <h2>Nejblížší akce</h2>
        <ul class="events">
            <li>Název: {{ akce[0].jmeno }}</li>
            <li>Místo: {{ akce[0].misto }}</li>
            <li>Datum: {{ akce[0].datum }}</li>
            <li><strong>Začátek akce: {{ akce[0].zacatek_akce }}</strong></li>
            <li><strong>Konec akce: {{ akce[0].konec_akce }}</strong></li>
            <li>Družiny:
                {% if druziny %}
                    {% for d in druziny if akce[0].id_akce == d.id_akce %}
                        {{ d.jmeno_druziny }}
                    {% endfor %}
                {% endif %}
            </li>
            <li>Vedoucí: 
                {% if akce[0].vedouci_jmeno %}
                    {% for a in akce %}
                        {% if a.id_akce == akce[0].id_akce %}
                            <a href="{{ url_for('unregistered_user.view_home_page') }}#home-vedouci">
                            {{ a.vedouci_jmeno }} {{ a.vedouci_prijmeni }} </a>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    {{ 'žádný' }}
                {% endif %}
            </li>
            <li class="event-description">Popis: {{ akce[0].popis }}</li>
            {% if session['role'] in ('vedouci', 'administrator') %}
                <li>    
                    <a href="{{ url_for('events_more.view_attendance_page') }}?id_akce={{ akce[0].id_akce }}&jmeno_akce={{ akce[0].jmeno }}">Docházka</a>
                    {% if akce[0].je_public == 0 %}
                        <a href="?id_akce={{ akce[0].id_akce }}">Zveřejnit</a>
                    {% endif %}
                    <a href="{{ url_for('events_more.edit_event') }}?id_akce={{ akce[0].id_akce }}">Upravit</a>
                    <a href="{{ url_for('events_more.delete_event') }}?id_akce={{ akce[0].id_akce }}">Smazat</a>
                </li>
        {% endif %}
        </ul>
        {% if session['role'] == 'dite' and je_prihlaseno_dite %}
            <h3>Speciální propozice</h3>
            <h4>Stravování</h4>
            <form class="special-food" action="#">
                <div>
                    <label for="svickova">Svíčková</label>
                    <input id="svickova" name="food_1" type="checkbox" value="svickova">
                </div>
                <div>
                    <label for="rizek">Řízek</label>
                    <input id="rizek" name="food_2" type="checkbox" value="rizek">
                </div>
                <div>
                    <label for="spenat">Špenát</label>
                    <input id="spenat" name="food_3" type="checkbox" value="spenat">
                </div>
                <div>
                    <label for="pstruh">Pstruh</label>
                    <input id="pstruh" name="food_4" type="checkbox" value="pstruh">
                </div>
                <div>
                    <input class="register" type="submit" value="Odeslat vedoucímu">
                </div>
            </form>
            <div>
                <h4>Co s sebou</h4>
                <ul>
                    <li>Svačina</li>
                    <li>Boty na turistiku</li>
                    <li>Batoh</li>
                    <li>Vhodné oblečení</li>
                </ul>
            </div>
        {% endif %}
        {% if session['role'] == 'rodic' and child_name != '' %}
            {% if dochazka.dochazka != 1 %}
                <button class="button", style="vertical-align:middle">
                    <a class="button-dochazka" href="?dojde=true&child_id={{ child_id }}&id_event={{ akce[0].id_akce }}">
                        <span>Přihlásit uživatele {{ child_name }} na akci</span>
                    </a>
                </button>
            {% elif dochazka.dochazka == 1 %}
                <button class="button", style="vertical-align:middle">
                    <a class="button-dochazka" href="?dojde=false&child_id={{ child_id }}&id_event={{ akce[0].id_akce }}">
                        <span>Odhlásit uživatele {{ child_name }} z akce</span>
                    </a>
                </button>
            {% endif %}
        {% endif %}
    </section>
    <section>
        <h2>Nasledující akce</h2>
            {% for a in akce[1:] %}
                <ul class="events">
                    <li>Název: {{ a.jmeno }}</li>
                    <li>Místo: {{ a.misto }}</li>
                    <li>Datum: {{ a.datum }}</li>
                    <li><strong>Začátek akce: {{ a.zacatek_akce }}</strong></li>
                    <li><strong>Konec akce: {{ a.konec_akce }}</strong></li>
                    <li>Družiny: 
                        {% if druziny %}
                            {% for d in druziny if a.id_akce == d.id_akce %}
                                {{ d.jmeno_druziny }}
                            {% endfor %}
                        {% endif %}
                    </li>
                    <li>Vedoucí:
                        {% if a.vedouci_jmeno %}
                            {% for vedouci in akce %}
                                {% if vedouci.id_akce == a.id_akce %} 
                                    <a href="{{ url_for('unregistered_user.view_home_page') }}#home-vedouci">
                                    {{ vedouci.vedouci_jmeno }} {{ vedouci.vedouci_prijmeni}}</a>
                                {% endif %}
                            {% endfor %}
                        {% else %}
                            {{ 'žádný' }}
                        {% endif %}
                    </li>
                    <li class="event-description">Popis: {{ a.popis }}</li>
                    {% if session['role'] in ('vedouci', 'administrator') %}
                        <li>    
                            <a href="{{ url_for('events_more.view_attendance_page') }}?id_akce={{ a.id_akce }}&jmeno_akce={{ a.jmeno }}">Docházka</a>
                            {% if a.je_public == 0 %}
                                <a href="?id_akce={{ a.id_akce }}">Zveřejnit</a>
                            {% endif %}
                            <a href="{{ url_for('events_more.edit_event') }}?id_akce={{ a.id_akce }}">Upravit</a>
                            <a href="{{ url_for('events_more.delete_event') }}?id_akce={{ a.id_akce }}">Smazat</a>
                        </li>
                    {% endif %}
                </ul>
                {#
                {% if session['role'] == 'rodic' and child_name != "" %}
                    {% if dochazka.dochazka != 1 %}
                        <button class="button", style="vertical-align:middle">
                            <a class="button-dochazka" href="?dojde=true&child_id={{ child_id }}&id_event={{ a.id_akce }}">
                                <span>Přihlásit uživatele {{ child_name }} na akci</span>
                            </a>
                        </button>
                    {% elif dochazka.dochazka == 1 %}
                        <button class="button", style="vertical-align:middle">
                            <a class="button-dochazka" href="?dojde=false&child_id={{ child_id }}&id_event={{ a.id_akce }}">
                                <span>Odhlásit uživatele {{ child_name }} z akce</span>
                            </a>
                        </button>
                    {% endif %}
                {% endif %}
               #}
            {% endfor%}
    </section>
{% endblock %}